config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "albums#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources:albums 

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_one_attached :cover_image
  has_one_attached :audio_data

  def self.tagged_with(name)
    Tag.find_by!(name: name).albums
  end
  def tag_list
   tags.map(&:name).join(', ')
  end
  def tag_list=(names)
    self.tags = names.split(',').map do |n|
    Tag.where(name: n.strip).first_or_create!
    end
  end

  validates :name, presence: true
  validates :audio_data, presence: true
  validates :cover_image,presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :album, through: :taggings
  end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_album,  except: [:index, :new, :create]
  before_action :check_owner,  only: [:edit]
  
    def index
      @q = Album.all.ransack(params[:q])
      @albums = @q.result(distinct: true)
    end

  def show
  end
  
  def new
    @album = Album.new
  end

  def create  
    @album = current_user.albums.new(album_params)
     if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end
  
  def update
    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def check_owner
    redirect_to root_path if @album.user != current_user
  end

  def album_params
    params.require(:album).permit(:name, :description,:allow_download,:cover_image,:audio_data,:tag_list )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_footer.html.erb
<footer class="bg-danger fixed-bottom text-center text-lg-start">  
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <%= link_to "Music Box",root_path,class:"tittle fw-bold text-decoration-none text-dark" %>
  </div>

</footer>

app/views/albums/_form.html.erb
<div class="d-flex justify-content-center form mt-5">
  <div class="  mt-5" >
    <%= form_with model: @album do |form| %>
      <div class="mt-5">
        <%= form.label :name%><br>
        <%= form.text_field :name %>   
      </div>
       <div class="mt-3">
         <%= form.label :description %><br>
         <%= form.text_area :description %>    
        </div>
      <div class="mt-3">
        <%= form.label :coverimage %><br>
        <%= form.file_field :cover_image %>    
      </div>
      <div class="mt-3">
       <%= form.label :tag_name %><br>
       <%= form.text_field :tag_list %>    
      </div>
      <div class="mt-3">  
        <%= form.label :audio_data %><br>
        <%= form.file_field :audio_data %>
      </div>
      <div class="mt-3">
        <%= form.submit %>
      </div>
      <div class="py-5">
      </div>
    <% end %>
  </div>
</div>

app/views/albums/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-danger sticky-top"> 
 <%= link_to "Music Box",root_path, class:"tittle fw-bold text-decoration-none text-dark" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-4">
        <% if user_signed_in? %>
          <li class="nav-item p-1 mx-4 ">
           <%= link_to "New Album",new_album_path, class:'text-decoration-none text-dark'%>
          </li>
          <li class="nav-item  p-1 ">
            <%= link_to "Logout ", destroy_user_session_path, data: {
            turbo_method: :delete,
            turbo_confirm:"Are you sure?"
          },class:'text-decoration-none text-dark btn-outline-danger'%>
            <%else %>
          <li class="nav-item p-1 link-decoration-none">
            <%= link_to "Login" , new_user_session_path ,class:'text-decoration-none text-dark  '%>
          </li>
        <% end %>
      </ul>
  </div>
</nav>


   

app/views/albums/edit.html.erb
<%=render "navbar"%>
<%= render "form", album: @album %>
<%=render "footer"%>

app/views/albums/index.html.erb
<%= render "navbar"%>
<form class="d-flex ms-auto mt-5  justify-content-center ">
    <%= search_form_for @q, url: root_path do |f| %>
      <%= f.search_field :tags_name_or_name_cont, placeholder: "Search By Tag or Name" %>
      <%= f.search_field :user_email_cont,placeholder:"search by email" %>
      <%= f.submit "Search", class:"btn btn-primary" %>
    <% end %>
 </form> 
<div class="container mt-5">
  <div class="row">  
    <% @albums.each do |album|%>
      <div class="col-lg-4 mt-3 link-decoration-none">
        <a href="/albums/<%= album.id %>" class="text-decoration-none text-black " > 
          <div class="card mt-3" style="width: 18rem;">
           <%= image_tag (album.cover_image) if album.cover_image.attached? %>
            <div class="card-body">
              <h5 class="card-title">
                <%= album.name  %>
                <h5>Tag:<%=album.tag_list%></h5>
              </h5>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>
<div class=" py-5">
</div>
<%= render "footer" %>

app/views/albums/new.html.erb
<%=render "navbar" %>
<%=render "form" , album:@album %>
<%= render "footer" %> 

app/views/albums/show.html.erb
<%=render "navbar"%>

<h1><%= @album.name %></h1>
<p><%= @album.description %></p>
<% @album.audio_data%>

<audio controls>
  <source src="<%= rails_blob_url(@album.audio_data)%>" type="<%= @album.audio_data.content_type %>">
</audio>

<ul>
  <%if current_user.present? && (current_user.id == @album.user_id)%>
    <div class="btn btn-warning mt-2">  <%= link_to "Edit", edit_album_path(@album) %></div>
    <div class="btn btn-danger mt-2 "> <%= link_to "Destroy", album_path(@album), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
  <%end%>
  <% if user_signed_in? %>
    <div class="btn btn-light mt-2 "><%=link_to "download",rails_blob_path(@album.audio_data, disposition: "attachment") %>
  <% end %>
</ul>

<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>